### ISSUE TITLE
Metrics end point?

### ISSUE THREAD

**Issue by pretty** [eliksir/baremetrics-php-api#2]
Hey! Thanks for making this! 👏

Just wondering, is the [metrics end point](https://developers.baremetrics.com/reference#show-summary) implemented on this library?

Thanks!

**Comment by fdanielsen** [comment]
Hi @pretty! I'm sorry but the metric endpoint has not been implemented yet. We don't have a use case for that currently, so I'm not sure when we'd be able to implement it. But if you look at the current resource definitions in the code, I think it should be fairly straight forward to understand how to implement the metrics resource. And we'd be happy to review and merge a pull request if you have the opportunity :)

**Comment by pretty** [comment]
Ok thank you @fdanielsen - I may just do that 😄
